### ISSUE TITLE
When trying to login as non existant user, a php error is thrown

### ISSUE THREAD

**Issue by cuotos** [mikehenken/Front-End-User-Login-Plugin--Feul-#2]
User XML storage, when logging in as a user that does not exists i get the following

Notice: Trying to get property of non-object in C:\Users\dan\Documents\htdocs\simple\plugins\user-login\class\Feul.php on line 380

$user_data is null if user.xml doesnt exist? is there error handling around this somewhere?

public function getUserData {
if($this->Storage == 'XML')
        {
            $user_xml = getXML(SITEUSERSPATH.$user.".xml");
            $user_data = $user_xml->$column;
            return $user_data;
        }

**Comment by tablatronix** [comment]
lol

**Comment by cuotos** [comment]
> lol

I actually just meant to edit it. It was a flashback to early in my Dev life, that's for sure!
